# Publishes the files in src to be uploaded to blob service
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: cp -r src/* $(Build.ArtifactStagingDirectory)
  displayName: 'Copy files'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
